//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obsessive.pl_csv_qty
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZZSPE_TWRXML_OBS
    {
        public int TWRXML_ID { get; set; }
        public string TWRXML_TWR_EAN { get; set; }
        public Nullable<int> TWRXML_ILOSC { get; set; }
    }
}
